# Generated by Django 3.2.4 on 2023-06-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0012_alter_layerrequestlog_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerrequestlog',
            name='request_type',
            field=models.CharField(choices=[('ALL', 'ALL'), ('PARTIAL', 'PARTIAL'), ('SINGLE', 'SINGLE')], default='ALL', max_length=40),
        ),
    ]
