# Generated by Django 3.2.23 on 2024-04-19 02:37

from django.db import migrations, models
import sqs.components.gisquery.models


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0014_auto_20240112_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='geojson',
        ),
        migrations.RemoveField(
            model_name='task',
            name='data',
        ),
        migrations.AddField(
            model_name='layer',
            name='attr_values',
            field=models.JSONField(default={}, verbose_name='Layer Attribute Values'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='geojson_file',
            field=models.FileField(default='dummy', upload_to=sqs.components.gisquery.models.geojson_file_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='retries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='parameters',
            field=models.TextField(blank=True, null=True, verbose_name='Script Parameters'),
        ),
        migrations.AlterField(
            model_name='task',
            name='script',
            field=models.TextField(verbose_name='Script name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('failed', 'Failed'), ('created', 'Created'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('error', 'Error'), ('max_queue_time', 'Max_Queue_Time_Reached'), ('max_retries', 'Max_Retries_Reached')], default='created', max_length=32, verbose_name='Task Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='system',
            field=models.CharField(max_length=100, verbose_name='Application name'),
        ),
    ]
