# Generated by Django 3.2.23 on 2024-08-02 06:29

from django.db import migrations, models
import django.db.models.deletion
import sqs.components.gisquery.models


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0015_auto_20240419_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='geojson_file',
        ),
        migrations.CreateModel(
            name='GeoJsonFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0, editable=False)),
                ('geojson_file', models.FileField(upload_to=sqs.components.gisquery.models.geojson_file_path)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geojson_files', to='sqs.layer')),
            ],
            options={
                'unique_together': {('geojson_file', 'index')},
            },
        ),
    ]
