# Generated by Django 3.2.23 on 2024-08-21 04:50

from django.db import migrations, models
import django.utils.timezone
import sqs.components.gisquery.models


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0016_auto_20240802_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='layer',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='GeoJsonFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0, editable=False)),
                ('geojson_file', models.FileField(max_length=512, upload_to=sqs.components.gisquery.models.geojson_file_path)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geojson_files', to='sqs.layer')),
            ],
        ),
#        migrations.AlterUniqueTogether(
#            name='geojsonfile',
#            unique_together=set(),
#        ),
    ]
