# Generated by Django 5.0.8 on 2024-08-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0017_auto_20240821_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='crs',
            field=models.CharField(default=4326, max_length=24),
            preserve_default=False,
        ),
    ]
