# Generated by Django 5.0.8 on 2024-08-28 04:50

import sqs.components.gisquery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0018_layer_crs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojsonfile',
            name='geojson_file',
            field=models.FileField(max_length=512, upload_to=sqs.components.gisquery.models.geojson_file_path),
        ),
    ]
