# Generated by Django 5.0.8 on 2024-09-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0019_alter_geojsonfile_geojson_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='request_type',
            field=models.CharField(choices=[('FULL', 'FULL'), ('PARTIAL', 'PARTIAL'), ('SINGLE', 'SINGLE'), ('REFRESH', 'REFRESH')], default='FULL', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layerrequestlog',
            name='request_type',
            field=models.CharField(choices=[('FULL', 'FULL'), ('PARTIAL', 'PARTIAL'), ('SINGLE', 'SINGLE'), ('REFRESH', 'REFRESH')], max_length=40),
        ),
    ]
